Sprint №9
DFater/PlayList-Maker pull request #6
Opened 2023-04-02 13:12 UTC by DFater

1. Добавил стили и темную тему.
2. Добавил функционал кнопкам в setting_activity
3. Реализовал search_activity
4. Реализовать сохранение текста поискового запроса в жизненном цикле search_activity.

2023-04-03 11:57 UTC, NoDopezzz requested changes

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +        val simpleTextWatcher = object : TextWatcher {
⏫ Зачастую, чтобы не избавиться от необходимости переопределения методов, которые мы не хотим использовать, можно создать интерфейс с дефолтной пустой реализацией этих методов.

Например, можно создать такой интерфейс:
```
private interface SimpleTextWatcher : TextWatcher {

        override fun afterTextChanged(s: Editable?) = Unit

        override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) = Unit

        override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) = Unit
    }
```

И в месте определения слушателя достаточно лишь переопределить только нужные методы

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +        return if (s.isNullOrEmpty()) {
⏫ Для изменения видимости элемента на экране можно использовать `extension` `View.isVisible`:

- `View.isVisible = true` соответствует `View.visibility = View.VISIBLE`
- `View.isVisible = false` соответствует `View.visibility = View.GONE`

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SettingsActivity.kt
> +            shareIntent.type = "text/plain"
⏫ Чтобы обращаться к одной переменной было проще, можно изменять ее внутри одной scope function - [apply](https://kotlinlang.org/docs/scope-functions.html#this).
Таким образом, создать нужный Intent можно так:
```
val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, getString(R.string.share_url))
            }
```

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/res/layout/activity_main.xml
> +        android:fontFamily="@font/ys_display_regular"
⏫ Для заголовка экрана предлагаю использовать созданный стиль - `upper_bar_text_view`

2023-04-03 11:57 UTC, kirillNay commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingStart">@dimen/medium_plus_size</item>
⚠️ Судя по макетам шрифт для заголовков экранов - `@font/ys_display_medium`

![image](https://user-images.githubusercontent.com/56832972/229500137-a4a886e7-459b-49f7-84c2-e18bfaf93fd4.png)

2023-04-03 11:57 UTC, kirillNay commented on app/src/main/res/values-night/themes.xml
> +        <item name="colorPrimary">@color/black</item>
⚠️ Цветом фон для темной темы является значение `#1A1B22`

<img width="548" alt="image" src="https://user-images.githubusercontent.com/56832972/229500899-e97ce943-33b6-4fd9-be92-9a35eede26db.png">

2023-04-03 11:57 UTC, kirillNay commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/ys_display_regular</item>
⚠️ Обрати внимание на `fontWeight`.  Судя по макетам fontWeight для элементов настроек равен **400**

<img width="682" alt="image" src="https://user-images.githubusercontent.com/56832972/229501812-5373d108-bd40-4000-bef1-4ee88eca6e6a.png">

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +    <style name="main_button_style" parent="Widget.MaterialComponents.Button">
⚠️ Чтобы избавиться от теней на кнопках достаточно стиль кнопок отнаследовать от `Widget.MaterialComponents.Button.UnelevatedButton`

2023-04-03 11:57 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +    </style>
⚠️ Обрати внимание на шрифт текста в кнопках. Судя по макетам он равен `@font/ys_display_medium`

<img width="756" alt="image" src="https://user-images.githubusercontent.com/56832972/229502284-8c21a3b1-47cd-4276-9273-f4a24f3e1120.png">

2023-04-06 16:50 UTC, DFater commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingStart="@dimen/small_size" />
Мне как то не очень нравится, что если я задаю стиль upper_bar_text_view, то мне приходится переопределять paddingStart

2023-04-07 02:04 UTC, NoDopezzz approved these changes

2023-04-07 02:04 UTC, NoDopezzz commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingStart="@dimen/small_size" />
Полностью с тобой согласен! Обычно (но не обязательно) в стили выносят атрибуты стилевого представления элементов - цвета, шрифты, точные размеры и т.д., а такие вещи как отступы держать в файлах верстки для большей гибкости.

Я бы тебе предложил либо `paddingStart` всегда определять в месте использования, либо же выделить два стиля для разных вариантов `paddingStart`, которые будут наследовать базовый стиль `upper_bar_text_view`

2023-04-08 10:55 UTC, merged